version: "3.8"
services:
  app:
    container_name: my-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@db:5432/mydb?schema=public
    depends_on:
      - db
  db:
    image: postgres
    container_name: my-db
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
